version: "3.8"

services:

  elasticsearch-single-node:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch-single-node
    hostname: elasticsearch-single-node
    environment:
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - node.name=elasticsearch-single-node
      - cluster.name=elasticsearch-single-node-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 19200:9200
    volumes:
      - ./plugins:/usr/share/elasticsearch/plugins
      - ./data/elasticsearch-single-node:/usr/share/elasticsearch/data

  elasticsearch-cluster-node-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch-cluster-node-1
    hostname: elasticsearch-cluster-node-1
    environment:
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - node.name=elasticsearch-cluster-node-1
      - cluster.name=elasticsearch-cluster
      - discovery.seed_hosts=elasticsearch-cluster-node-1,elasticsearch-cluster-node-2,elasticsearch-cluster-node-3
      - cluster.initial_master_nodes=elasticsearch-cluster-node-1,elasticsearch-cluster-node-2,elasticsearch-cluster-node-3
      - node.roles=master,data
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./plugins:/usr/share/elasticsearch/plugins
      - ./data/elasticsearch-cluster-node-1:/usr/share/elasticsearch/data

  elasticsearch-cluster-node-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch-cluster-node-2
    hostname: elasticsearch-cluster-node-2
    environment:
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - node.name=elasticsearch-cluster-node-2
      - cluster.name=elasticsearch-cluster
      - discovery.seed_hosts=elasticsearch-cluster-node-1,elasticsearch-cluster-node-2,elasticsearch-cluster-node-3
      - cluster.initial_master_nodes=elasticsearch-cluster-node-1,elasticsearch-cluster-node-2,elasticsearch-cluster-node-3
      - node.roles=master,data
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./plugins:/usr/share/elasticsearch/plugins
      - ./data/elasticsearch-cluster-node-2:/usr/share/elasticsearch/data

  elasticsearch-cluster-node-3:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch-cluster-node-3
    hostname: elasticsearch-cluster-node-3
    environment:
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - node.name=elasticsearch-cluster-node-3
      - cluster.name=elasticsearch-cluster
      - discovery.seed_hosts=elasticsearch-cluster-node-1,elasticsearch-cluster-node-2,elasticsearch-cluster-node-3
      - cluster.initial_master_nodes=elasticsearch-cluster-node-1,elasticsearch-cluster-node-2,elasticsearch-cluster-node-3
      - node.roles=master,data
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./plugins:/usr/share/elasticsearch/plugins
      - ./data/elasticsearch-cluster-node-3:/usr/share/elasticsearch/data

  elasticsearch-coordinator:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch-coordinator
    hostname: elasticsearch-coordinator
    environment:
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - node.name=elasticsearch-coordinator
      - cluster.name=elasticsearch-cluster
      - discovery.seed_hosts=elasticsearch-cluster-node-1,elasticsearch-cluster-node-2,elasticsearch-cluster-node-3
      - cluster.initial_master_nodes=elasticsearch-cluster-node-1,elasticsearch-cluster-node-2,elasticsearch-cluster-node-3
      - node.roles=[]
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 29200:9200
    volumes:
      - ./plugins:/usr/share/elasticsearch/plugins
