version: "3.8"

services:

# Kafka Single 
  kafka-single-node:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-single-node
    hostname: kafka-single-node
    environment:
      # 시간 및 로케일 설정
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
      # 기본 Kafka 설정
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_NUM_PARTITIONS=1
      # 리스너 설정
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092,CONTROLLER://0.0.0.0:29092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-single-node:9092,EXTERNAL://localhost:19090
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      # KRaft 설정 (단일 노드)
      - CLUSTER_ID=kafka-single-cluster-0
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-single-node:29092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - 19092:19092
    volumes:
      - ./data/kafka-single-node:/var/lib/kafka/data

# Kafka Cluster
  kafka-cluster-node-1:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-cluster-node-1
    hostname: kafka-cluster-node-1
    environment:
      # 시간 및 로케일 설정
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
      # 기본 Kafka 설정
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_NUM_PARTITIONS=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      # 리스너 설정
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092,CONTROLLER://0.0.0.0:29092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-cluster-node-1:9092,EXTERNAL://localhost:19091
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      # KRaft 설정 (단일 노드)
      - CLUSTER_ID=kafka-multiple-cluster
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-cluster-node-1:29092,2@kafka-cluster-node-2:29092,3@kafka-cluster-node-3:29092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - 29091:19092
    volumes:
      - ./data/kafka-cluster-node-1:/var/lib/kafka/data

  kafka-cluster-node-2:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-cluster-node-2
    hostname: kafka-cluster-node-2
    environment:
      # 시간 및 로케일 설정
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
      # 기본 Kafka 설정
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_NUM_PARTITIONS=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      # 리스너 설정
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092,CONTROLLER://0.0.0.0:29092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-cluster-node-2:9092,EXTERNAL://localhost:19092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      # KRaft 설정 (단일 노드)
      - CLUSTER_ID=kafka-multiple-cluster
      - KAFKA_NODE_ID=2
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-cluster-node-1:29092,2@kafka-cluster-node-2:29092,3@kafka-cluster-node-3:29092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - 29092:19092
    volumes:
      - ./data/kafka-cluster-node-2:/var/lib/kafka/data

  kafka-cluster-node-3:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-cluster-node-3
    hostname: kafka-cluster-node-3
    environment:
      # 시간 및 로케일 설정
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
      # 기본 Kafka 설정
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_NUM_PARTITIONS=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      # 리스너 설정
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092,CONTROLLER://0.0.0.0:29092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-cluster-node-3:9092,EXTERNAL://localhost:19093
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      # KRaft 설정 (단일 노드)
      - CLUSTER_ID=kafka-multiple-cluster
      - KAFKA_NODE_ID=2
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-cluster-node-1:29092,2@kafka-cluster-node-2:29092,3@kafka-cluster-node-3:29092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - 29093:19092
    volumes:
      - ./data/kafka-cluster-node-3:/var/lib/kafka/data
