version: "3.8"

services:

# Redis Single 
  redis-single-node:
    image: redis:7.2
    container_name: redis-single-node
    hostname: redis-single-node
    environment:
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
    entrypoint: |
      redis-server --appendonly yes
    ports:
      - 16379:6379
    volumes:
      - ./data/redis-single-node:/data

# Redis Cluster
  redis-cluster-node-1:
    image: redis:7.2
    container_name: redis-cluster-node-1
    hostname: redis-cluster-node-1
    environment:
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
    entrypoint: |
      redis-server 
        --appendonly yes
        --cluster-enabled yes
        --cluster-config-file nodes.conf
        --cluster-node-timeout 3000
    volumes:
      - ./data/redis-cluster-node-1:/data

  redis-cluster-node-2:
    image: redis:7.2
    container_name: redis-cluster-node-2
    hostname: redis-cluster-node-2
    environment:
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
    entrypoint: |
      redis-server 
        --appendonly yes
        --cluster-enabled yes
        --cluster-config-file nodes.conf
        --cluster-node-timeout 3000
    volumes:
      - ./data/redis-cluster-node-2:/data

  redis-cluster-node-3:
    image: redis:7.2
    container_name: redis-cluster-node-3
    hostname: redis-cluster-node-3
    environment:
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
    entrypoint: |
      redis-server 
        --appendonly yes
        --cluster-enabled yes
        --cluster-config-file nodes.conf
        --cluster-node-timeout 3000
    volumes:
      - ./data/redis-cluster-node-3:/data

  redis-cluster-node-4:
    image: redis:7.2
    container_name: redis-cluster-node-4
    hostname: redis-cluster-node-4
    environment:
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
    entrypoint: |
      redis-server 
        --appendonly yes
        --cluster-enabled yes
        --cluster-config-file nodes.conf
        --cluster-node-timeout 3000
    volumes:
      - ./data/redis-cluster-node-4:/data

  redis-cluster-node-5:
    image: redis:7.2
    container_name: redis-cluster-node-5
    hostname: redis-cluster-node-5
    environment:
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
    entrypoint: |
      redis-server 
        --appendonly yes
        --cluster-enabled yes
        --cluster-config-file nodes.conf
        --cluster-node-timeout 3000
    volumes:
      - ./data/redis-cluster-node-5:/data

  redis-cluster-node-6:
    image: redis:7.2
    container_name: redis-cluster-node-6
    hostname: redis-cluster-node-6
    environment:
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
    entrypoint: |
      redis-server 
        --appendonly yes
        --cluster-enabled yes
        --cluster-config-file nodes.conf
        --cluster-node-timeout 3000
    volumes:
      - ./data/redis-cluster-node-6:/data

  redis-cluster-init:
    image: redis:7.2
    container_name: redis-cluster-init
    depends_on:
      - redis-cluster-node-1
      - redis-cluster-node-2
      - redis-cluster-node-3
      - redis-cluster-node-4
      - redis-cluster-node-5
      - redis-cluster-node-6
    entrypoint: |
      redis-cli --cluster --host redis-cluster-node-1 --port 6379 cluster info | grep -q "cluster_state:ok" ||
      redis-cli --cluster create --cluster-yes --cluster-replicas 1
        redis-cluster-node-1:6379
        redis-cluster-node-2:6379
        redis-cluster-node-3:6379
        redis-cluster-node-4:6379
        redis-cluster-node-5:6379
        redis-cluster-node-6:6379

  redis-predixy:
    image: haandol/predixy:latest
    container_name: redis-predixy
    hostname: redis-predixy
    ports:
      - 17617:7617
    depends_on:
      - redis-cluster-init
    volumes:
      - ./predixy-conf/cluster.conf:/etc/predixy/conf/cluster.conf
